---
resource_types:
      - name: google-cloud-storage
        type: docker-image
        source:
            repository: frodenas/gcs-resource

resources:
- name: git-bosh-release
  type: git
  source:
    uri: {{git-bosh-release}}
    branch: {{git-bosh-release-branch}}

- name: version
  type: semver
  source:
    driver: gcs
    bucket: concourse-bosh-releases
    initial_version: 0.0.1
    key: current-version
    json_key: ((google_account_creds))

- name: gcs-bucket
  type: google-cloud-storage
  source:
      bucket: concourse-bosh-releases
      json_key: ((google_account_creds))
      regexp: releases/release-(.*).tgz

jobs:
- name: job-bosh-create-release-upload
  public: true
  serial: true
  plan:
    - get: bosh-release
      resource: git-bosh-release
      trigger: true
    - get: version
      params: {bump: patch}
    - task: create-release
      input_mapping:
        bosh-release: bosh-release
      config:
          platform: linux
          image_resource: 
              type: docker-image
              source:
                  repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          inputs:
            - name: bosh-release
            - name: version
          outputs:
            - name: release
          run:
            path: bash
            args: 
                - -exc
                - |
                    ls -la
                    VERSION=$(cat version/version)
                    bosh -n create-release --dir=bosh-release --tarball=release/release-$VERSION.tgz

    - put: gcs-bucket
      params: { file: release/release-*.tgz }

    - put: version
      params: { file: version/version }
